Rebuild r-pdftools for poppler v24.09.0
AnacondaRecipes/aggregateR pull request #7
Opened 2024-11-11 14:56 UTC by bwingconda

r-pdftools 3.4.0

**Destination channel:** defaults

### Links

- [PKG-6112](https://anaconda.atlassian.net/browse/PKG-6112)
- [Upstream repository](https://github.com/ropensci/pdftools/tree/master)

### Explanation of changes:

- Update poppler pinnings for latest version

2024-11-11 16:00 UTC, skupr-anaconda approved these changes

2024-11-11 18:40 UTC, Jrice1317 approved these changes
Assuming pinning an older version of `poppler` for s390x only is not an option and/or not worth the effort, this seems okay to me.

2024-11-11 18:41 UTC, Jrice1317 requested changes
Once builds pass

2024-11-11 19:19 UTC, bwingconda commented
I have been told packages within aggregateR are manual builds. The CI errors indicate the build is trying to clone aggregateR within aggregate and then build all of aggregateR. To me, this seems like the CI is not currently capable of handling repos that exist outside of aggregate, such as this one.

2024-11-13 17:35 UTC, ELundby45 approved these changes

2024-11-13 17:35 UTC, Jrice1317 approved these changes

2024-11-13 20:07 UTC, merged